version: '2.4'
services:
  restapi:
    build: 
      context: ./
    ports:
      - 8080:80
    volumes:
      - ./OpenImis.RestApi/config:/app/config
      - ./OpenImis.RestApi/logs:/app/log
      - ./OpenImis.RestApi/Certificates:/app/wwwRoot/Certificates
    restart: always